In [100]:
import urllib
from bs4 import BeautifulSoup
import re
import pandas as pd

## Incident Achieve

In [116]:
webpages = []
for i in range(1,138):
    webpages.append("https://incidentnews.noaa.gov/browse/date?page=" + str(i))

In [264]:
webpages[0]

'https://incidentnews.noaa.gov/browse/date?page=1'

In [277]:
page = urllib.request.urlopen(webpages[0])

#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page, 'lxml')

#get all links appear on page
all_links = soup.find_all('a', class_="name")
all_locations = soup.find_all('span', class_="location")
all_dates = soup.find_all('td', class_="date")

In [278]:
all_locations

[<span class="location">175 Sports Marina Rd, Venice, LA 70091, USA</span>,
 <span class="location">Venice, LA 70091, USA</span>,
 <span class="location">Port of Oakland, CA 94607, USA</span>,
 <span class="location">Vista Court, Highlands, TX 77049, USA</span>,
 <span class="location"></span>,
 <span class="location">SMI149</span>,
 <span class="location">Breton Sound, LA, USA</span>,
 <span class="location">1801 S Gulfway Dr, Port Arthur, TX 77640, USA</span>,
 <span class="location">Sanak Islands, Alaska</span>,
 <span class="location">GIWW MM 245, Sulphur, LA 70665, USA</span>,
 <span class="location">Breton Sound, LA, USA</span>,
 <span class="location">S Walton Dr, Chicago, IL 60617, USA</span>,
 <span class="location">30 nm east of Kaneohe Bay, Oahu, HI 96770, USA</span>,
 <span class="location">Texas Coast</span>,
 <span class="location">between Burrows &amp; Bird Island near Anacortes, WA, USA</span>,
 <span class="location">Cypress Cove Area, Venice, LA 70091, USA</span>,
 <span class="location">S of Block Island, RI</span>,
 <span class="location">East Breaks Area</span>,
 <span class="location">Unalaska, AK</span>,
 <span class="location">Unakwik Inlet,  Northern Prince William Sound, Alaska</span>,
 <span class="location">Ferry Dock, Sault Ste. Marie, MI 49783, USA</span>,
 <span class="location">Sitka, AK</span>,
 <span class="location">Offshore Louisiana</span>,
 <span class="location">Pier G, Port of Long Beach, CA 90802, USA</span>,
 <span class="location">Offshore Louisiana</span>]

In [285]:
all_dates

[<td class="date">2017-Sep-23</td>,
 <td class="date">2017-Sep-22</td>,
 <td class="date">2017-Sep-22</td>,
 <td class="date">2017-Sep-21</td>,
 <td class="date">2017-Sep-19</td>,
 <td class="date">2017-Sep-19</td>,
 <td class="date">2017-Sep-19</td>,
 <td class="date">2017-Sep-19</td>,
 <td class="date">2017-Sep-07</td>,
 <td class="date">2017-Sep-05</td>,
 <td class="date">2017-Aug-27</td>,
 <td class="date">2017-Aug-25</td>,
 <td class="date">2017-Aug-25</td>,
 <td class="date">2017-Aug-24</td>,
 <td class="date">2017-Aug-24</td>,
 <td class="date">2017-Aug-23</td>,
 <td class="date">2017-Aug-15</td>,
 <td class="date">2017-Aug-14</td>,
 <td class="date">2017-Aug-13</td>,
 <td class="date">2017-Aug-10</td>,
 <td class="date">2017-Aug-10</td>,
 <td class="date">2017-Aug-09</td>,
 <td class="date">2017-Aug-08</td>,
 <td class="date">2017-Aug-06</td>,
 <td class="date">2017-Aug-05</td>]

In [286]:
states = []
dates =[]
for i,v in enumerate(all_locations):
    states.append(re.findall(r'[A-Z]{2}(?=\s)', str(v)))
    dates.append(re.findall(r'(?<=\>).*(?=\<)', str(all_dates[i])))

In [287]:
dates

[['2017-Sep-23'],
 ['2017-Sep-22'],
 ['2017-Sep-22'],
 ['2017-Sep-21'],
 ['2017-Sep-19'],
 ['2017-Sep-19'],
 ['2017-Sep-19'],
 ['2017-Sep-19'],
 ['2017-Sep-07'],
 ['2017-Sep-05'],
 ['2017-Aug-27'],
 ['2017-Aug-25'],
 ['2017-Aug-25'],
 ['2017-Aug-24'],
 ['2017-Aug-24'],
 ['2017-Aug-23'],
 ['2017-Aug-15'],
 ['2017-Aug-14'],
 ['2017-Aug-13'],
 ['2017-Aug-10'],
 ['2017-Aug-10'],
 ['2017-Aug-09'],
 ['2017-Aug-08'],
 ['2017-Aug-06'],
 ['2017-Aug-05']]

In [276]:
len(all_links), len(states)

(25, 25)

In [274]:
states

[['LA'],
 ['LA'],
 ['CA'],
 ['TX'],
 [],
 [],
 [],
 ['TX'],
 [],
 ['WW', 'MM', 'LA'],
 [],
 ['IL'],
 ['HI'],
 [],
 [],
 ['LA'],
 [],
 [],
 [],
 [],
 ['MI'],
 [],
 [],
 ['CA'],
 []]

In [291]:
def page_iteration(webpages):
    """return all incident events of each page"""
    incident_pages = []
    states = []
    dates = []
    for i,webpage in enumerate(webpages):
        #Query the website and return the html to the variable 'page'
        page = urllib.request.urlopen(webpage)

        #Parse the html in the 'page' variable, and store it in Beautiful Soup format
        soup = BeautifulSoup(page, 'lxml')

        #get all links appear on page
        all_links = soup.find_all('a', class_="name")
        all_locations = soup.find_all('span', class_="location")
        all_dates = soup.find_all('td', class_="date")
        prefix = "https://incidentnews.noaa.gov"
        
        for j,link in enumerate(all_links):
            incident_pages.append(prefix + link.get("href"))
            states.append(re.findall(r'[A-Z]{2}(?=\s)', str(all_locations[j])))
            dates.append(re.findall(r'(?<=\>).*(?=\<)', str(all_dates[j])))
        


    return incident_pages, states, dates

In [292]:
incident_pages, states, dates = page_iteration(webpages)

In [293]:
incident_pages[:10]

['https://incidentnews.noaa.gov/incident/9581',
 'https://incidentnews.noaa.gov/incident/9579',
 'https://incidentnews.noaa.gov/incident/9580',
 'https://incidentnews.noaa.gov/incident/9578',
 'https://incidentnews.noaa.gov/incident/9574',
 'https://incidentnews.noaa.gov/incident/9572',
 'https://incidentnews.noaa.gov/incident/9575',
 'https://incidentnews.noaa.gov/incident/9573',
 'https://incidentnews.noaa.gov/incident/9569',
 'https://incidentnews.noaa.gov/incident/9565']

In [295]:
len(incident_pages), len(states), len(dates)

(3410, 3410, 3410)

In [98]:
# page = urllib.request.urlopen(incident_pages[0])
# soup = BeautifulSoup(page)

# web_content = soup.prettify()
# print(web_content)
# texts = soup.find_all('p', class_="sub")
# info = soup.find_all('td')

In [298]:
def extract_info(page):
    """extract metric names and metric value on a single page"""
    soup = BeautifulSoup(page, "lxml")
    texts = soup.find_all('p', class_="sub")
    info = soup.find_all('td')
   
    texts = re.findall(r'(?<=strong\>\:).*', str(texts))
#     texts = re.sub(r'\]|\[|\\', "", str(texts))
#     print(texts)
    #clean info
    info = re.sub(r'\<.*?\>',"",str(info))
    info = re.sub(r'\:\s*,', ":", str(info))
    info = re.sub(r'\[|\]', "", str(info))
    
    #get metrics
    metrics = re.findall(r'(?<=,\s)[A-Z]\w+[^,]*?\:|^.*?\:', str(info))
    metrics = [item.replace(":","") for item in metrics]
    metrics.append('Text')
    
    #get values
    values = re.findall(r'(?<=\:\s).*?(?=,)|(?<=\:\s).*?(?=$)', str(info))
    values.append(texts)
    same_size = False
    if (len(metrics) == len(values)):
        same_size = True        
    return metrics, values, same_size

In [303]:
def multi_page_data_extraction(incident_pages):
    """return a dataframe contain all data on a single page"""
    dfs = []
    size_unmatch = []
    for i,webpage in enumerate(incident_pages):
        page = urllib.request.urlopen(webpage)
        metrics, values, same_size = extract_info(page)
        if same_size == True:
            df = pd.DataFrame(data=[values], columns=metrics)
            dfs.append(df)
        else:
            size_unmatch.append(i)
    return dfs, size_unmatch

In [304]:
dfs, size_unmatch = multi_page_data_extraction(incident_pages)
df = pd.concat(dfs, axis=0).reset_index().drop(['index'], axis=1)

KeyboardInterrupt:

In [254]:
size_unmatch[:10]

[2266]

In [255]:
incident_pages[2266]

'https://incidentnews.noaa.gov/incident/5080'

In [256]:
w = incident_pages[2266]
p = extract_info(urllib.request.urlopen(w))
p

(['Products of concern',
  'Total amount at risk of spill',
  'Latitude (approximate)',
  'Longitude (approximate)',
  'On-Water Recovery',
  'Shoreline Cleanup',
  'Dispersants',
  'In-Situ Burn',
  'Bioremediation',
  'Text'],
 ['180',
  '43° 38.82′ North',
  '70° 17.39′ West',
  'Unknown/Not applicable',
  'Unknown/Not applicable',
  'Applied',
  'Unknown/Not applicable',
  'Unknown/Not applicable',
  [' On the afternoon of September 27, 1996, the motor tanker, Julie N, owned and operated by Maritime Overseas Corporation,  entered Portland Harbor under pilotage carrying a cargo of #2 home heating fuel (HHF).  The pilot prepared for passage through the "Million Dollar Bridge," an extremely narrow draw bridge, affording less than five feet of clearance on either side of the vessel\'s mid-section.  Accounting for a rising tide and southwesterly winds, the pilot approached the opening from the northern portion of the Fore River and misspoke the helm command.  By the time the order could be corrected, less than a minute later, the vessel was committed and allision (a moving object hitting a stationary one) imminent.']],
 False)

In [305]:
df

,Bioremediation,Cargo,Dispersants,In-Situ Burn,Latitude (approximate),Longitude (approximate),On-Water Recovery,Primary threat,Products of concern,Shoreline Cleanup,Tags,Text,Total amount at risk of spill
0,Unknown/Not applicable,NaN,Unknown/Not applicable,Unknown/Not applicable,29° 19.08′ North,89° 17.55′ West,Applied,Oil,Oil+ produced water,Applied,NaN,"[ On September 23, 2017, the USCG Sector New O...",1 barrels
1,Unknown/Not applicable,NaN,Unknown/Not applicable,Unknown/Not applicable,29° 16.52′ North,89° 14.58′ West,Unknown/Not applicable,Oil,Oil,Applied,NaN,"[ On September 22, 2017, the USCG Sector New O...",5 barrels
2,Unknown/Not applicable,NaN,Unknown/Not applicable,Unknown/Not applicable,37° 48.64′ North,122° 19.53′ West,Applied,Other,Shipping containers,Unknown/Not applicable,NaN,"[ On September 22, 2017, the USCG Sector San F...",NaN
3,NaN,NaN,NaN,NaN,29° 49.83′ North,95° 5.25′ West,NaN,Chemical,Diluted Petromeen (0.05-0.07%),NaN,NaN,"[ On September 21, 2017, the USCG Sector Houst...",4500 barrels
4,NaN,NaN,NaN,NaN,43° 24.00′ North,69° 19.80′ West,NaN,Oil,NaN,NaN,NaN,"[ On September 19, 2017, the USCG Sector North...",NaN
5,NaN,NaN,NaN,NaN,28° 14.50′ North,92° 7.68′ West,NaN,Oil,Oil,NaN,NaN,"[ On September 19, 2017, the USCG MSU Houma co...",unknown gallons
6,NaN,NaN,NaN,NaN,29° 39.94′ North,89° 29.74′ West,NaN,Oil,Oil,NaN,NaN,"[ On September 19, 2017, the USCG Sector New O...",10 gallons
7,NaN,NaN,NaN,NaN,29° 51.94′ North,93° 58.02′ West,NaN,Oil,Vacuum Gas Oil (VGO),NaN,NaN,"[ On September 19, 2017, the USCG MSU Port Art...",unknown gallons
8,NaN,NaN,NaN,NaN,54° 22.48′ North,162° 30.86′ West,NaN,Oil,diesel,NaN,NaN,"[ On September 6, 2017, the F/V Provider beac...",550 gallons
9,Unknown/Not applicable,NaN,Unknown/Not applicable,Unknown/Not applicable,30° 3.56′ North,93° 22.12′ West,Applied,Oil,Marine Diesel,Unknown/Not applicable,NaN,"[ On September 5, 2017, the USCG MSU Lake Char...",3500 gallons
10,NaN,NaN,NaN,NaN,29° 33.47′ North,89° 19.50′ West,NaN,Oil,Oil,NaN,NaN,"[ On August 27, 2017, the USCG Sector New Orle...",235 barrels
11,NaN,NaN,NaN,NaN,41° 43.86′ North,87° 30.34′ West,NaN,Oil,NaN,NaN,NaN,"[ On August 25th, 2017, USCG MSU Chicago conta...",NaN
12,NaN,NaN,NaN,NaN,21° 22.20′ North,157° 11.40′ West,NaN,Oil,Marine diesel,NaN,NaN,"[ On August 25, 2017, the USCG Sector Honolulu...",5000 gallons
13,NaN,NaN,NaN,NaN,27° 47.40′ North,95° 36.60′ West,NaN,Other,NaN,NaN,NaN,"[ At approximately August 24, 2017, Tropical ...",NaN
14,NaN,NaN,NaN,NaN,48° 28.98′ North,122° 43.80′ West,NaN,Other,NaN,NaN,NaN,"[ On August 24, 2017, the USCG Sector Puget So...",NaN
15,Unknown/Not applicable,NaN,Unknown/Not applicable,Unknown/Not applicable,29° 15.07′ North,89° 21.48′ West,Applied,Oil,Marine Diesel,Unknown/Not applicable,NaN,"[ On August 23, 2017, the USCG Sector New Orle...",2300 gallons
16,NaN,NaN,NaN,NaN,40° 39.16′ North,71° 0.73′ West,NaN,Oil,unknown,NaN,NaN,"[ On August 15, 2017, the USCG Sector Long Isl...",NaN
17,NaN,NaN,NaN,NaN,27° 45.62′ North,94° 6.30′ West,NaN,Oil,potential oil,NaN,NaN,"[ On August 14, 2017, the USCG Sector Houston ...",unknown gallons
18,NaN,NaN,NaN,NaN,53° 50.39′ North,166° 35.59′ West,NaN,Oil,diesel,NaN,NaN,"[ On August 5, 2017, the FV Akutan left Dillin...",30000 gallons
19,NaN,NaN,NaN,NaN,60° 57.01′ North,147° 35.10′ West,NaN,Oil,diesel,NaN,NaN,"[ On August 10, 2017, the 51-foot F/V Stoic st...",1000 gallons
20,NaN,NaN,NaN,NaN,46° 29.33′ North,84° 18.10′ West,NaN,Oil,Diesel,NaN,NaN,"[ At 2340 on August 9th, 2017, M/V Calumet a 6...",105000 gallons
21,NaN,NaN,NaN,NaN,57° 17.28′ North,135° 36.22′ West,NaN,Oil,diesel,NaN,NaN,"[ On August 6, 2017, the commercial fishing ve...",600 gallons
22,NaN,NaN,NaN,NaN,28° 56.15′ North,88° 58.20′ West,NaN,Oil,NaN,NaN,NaN,"[ On August 8, 2017, Sector New Orleans contac...",NaN
23,Unknown/Not applicable,NaN,Unknown/Not applicable,Unknown/Not applicable,33° 44.62′ North,118° 12.12′ West,Unknown/Not applicable,Chemical,Propyl Acetate,Applied,NaN,"[ On August 6, 2017, the USCG Sector Los Angel...",6600 gallons
24,NaN,NaN,NaN,NaN,28° 59.25′ North,88° 55.68′ West,NaN,Oil,NaN,NaN,NaN,"[ On August 5, 2017, USCG Sector New Orleans ...",NaN
25,NaN,NaN,NaN,NaN,60° 9.41′ North,147° 45.16′ West,NaN,Oil,diesel,NaN,NaN,"[ On 4-Aug-2017, the F/V All In capsized off t...",400 gallons
26,NaN,NaN,NaN,NaN,30° 14.70′ North,89° 11.80′ West,NaN,Chemical,anhydrous ammonia,NaN,NaN,"[ On August 3, 2017, the USCG Sector Mobile ...",2500 tons
27,NaN,NaN,NaN,NaN,70° 23.13′ North,148° 31.09′ West,NaN,Oil,unknown,NaN,NaN,"[ On July 30, 2017, the YNG 15, an old WWII er...",unkown gallons
28,NaN,NaN,NaN,NaN,19° 6.64′ North,159° 59.34′ East,NaN,Other,NaN,NaN,NaN,"[ On July 31, 2017, the Emergency Response Div...",NaN
29,NaN,NaN,NaN,NaN,58° 3.37′ North,153° 24.66′ West,NaN,Oil,diesel,NaN,NaN,"[ On July 24, 2017, the USCG MSD Kodiak contac...",700 gallons
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3379,Unknown/Not applicable,NaN,Applied,Applied,43° 22.00′ North,8° 23.00′ West,Unknown/Not applicable,Oil,Light Arabian crude oil,Unknown/Not applicable,Collision,"[ On May 12, 1976, the Tank Vessel Urquiola st...",9
3380,NaN,NaN,NaN,NaN,1° 30.00′ North,79° 30.00′ West,NaN,NaN,Orito Crude Oil,NaN,NaN,"[ The tank vessel St. Peter departed Tumaco, C...",NaN
3381,Unknown/Not applicable,NaN,Unknown/Not applicable,Applied,37° 49.00′ North,76° 11.00′ West,Unknown/Not applicable,NaN,No. 6 Fuel Oil,Unknown/Not applicable,NaN,"[ On February 2, 1976, the petroleum transport...",250
3382,NaN,NaN,NaN,NaN,18° 28.00′ North,66° 8.00′ West,NaN,NaN,Bunker C,NaN,NaN,"[ On December 9, 1975, the tank barge Z-102 gr...",323
3383,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,50° 59.00′ North,1° 35.00′ West,Unknown/Not applicable,NaN,Iranian light crude oil,Unknown/Not applicable,NaN,[ Shortly after midnight on the morning of Nov...,588
3384,NaN,NaN,NaN,NaN,28° 20.00′ North,93° 3.00′ West,NaN,NaN,Arabian Crude oil,NaN,NaN,"[ At 0130 on August 15, 1975, the M/V Globtik ...",294
3385,Unknown/Not applicable,NaN,Applied,Applied,22° 54.00′ South,43° 10.00′ West,Unknown/Not applicable,NaN,Crude Oil,Unknown/Not applicable,NaN,"[ The Tarik Ibn Ziyad grounded on March 26, 19...",NaN
3386,NaN,NaN,NaN,NaN,39° 49.00′ North,75° 25.00′ West,NaN,NaN,paraffin,NaN,NaN,"[ At approximately 0030, on January 31, 1975, ...",84
3387,Unknown/Not applicable,NaN,Applied,Applied,41° 9.00′ North,8° 50.00′ West,Unknown/Not applicable,NaN,Iranian crude,Unknown/Not applicable,NaN,"[ On January 29, 1975, the Jakob Maersk struck...",NaN
3388,NaN,NaN,NaN,NaN,52° 34.00′ South,69° 41.00′ West,NaN,NaN,Light Arabian Crude Oil,NaN,NaN,"[ On August 9, 1974, at 2220, the VLCC (Very L...",NaN
3389,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,10° 30.00′ North,62° 0.00′ West,Unknown/Not applicable,NaN,Venezuelan crude oil,Unknown/Not applicable,NaN,"[ On the afternoon of August 8, 1973, the Trin...",NaN
3390,NaN,NaN,NaN,NaN,18° 0.00′ North,67° 15.00′ West,NaN,NaN,Venezuelan crude oil,NaN,NaN,"[ At 0255 on March 18, 1973, the Zoe Colocotro...",1
3391,NaN,NaN,NaN,NaN,29° 38.00′ North,94° 58.00′ West,NaN,NaN,Louisiana crude,NaN,NaN,"[ On March 9, 1973 at approximately 1326, the ...",420
3392,NaN,NaN,NaN,NaN,25° 18.00′ North,57° 34.00′ East,NaN,NaN,Crude Oil,NaN,NaN,"[ Early on the morning of December 19, 1972, t...",NaN
3393,NaN,NaN,NaN,NaN,43° 40.00′ North,70° 10.00′ West,NaN,NaN,No. 6 Fuel Oil,NaN,NaN,"[ In the early morning of July 22, 1972, the t...",100
3394,NaN,NaN,NaN,NaN,40° 15.00′ North,75° 38.00′ West,NaN,NaN,Waste oil and sludge,NaN,NaN,"[ On June 22, 1972, 140,000-190,000 barrels of...",7
3395,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,35° 0.00′ South,20° 2.00′ East,Unknown/Not applicable,NaN,Arabian crude oil,Unknown/Not applicable,NaN,"[ On the morning of February 27, 1971, the tan...",NaN
3396,NaN,NaN,NaN,NaN,37° 49.00′ North,122° 30.00′ West,NaN,NaN,Bunker C,NaN,NaN,"[ On January 18, 1971 at 0141, the tank vessel...",NaN
3397,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,28° 46.00′ North,90° 10.00′ West,Unknown/Not applicable,Oil,Crude oil,Unknown/Not applicable,Wellhead,"[ On December 1, 1970, Shell Oil Co. Platform ...",NaN
3398,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,50° 35.00′ North,1° 20.00′ West,Unknown/Not applicable,Oil,Nigerian crude oil,Unknown/Not applicable,Collision,"[ On the evening of October 23, 1970, the tank...",1
3399,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,29° 23.00′ North,88° 59.00′ West,Unknown/Not applicable,Oil,crude oil,Unknown/Not applicable,NaN,[ The Chevron Main Pass Block 41C platform cau...,NaN
3400,Unknown/Not applicable,NaN,Applied,Applied,45° 28.00′ North,61° 6.00′ West,Unknown/Not applicable,Oil,Bunker C Oil,Unknown/Not applicable,Grounding,"[ On February 4, 1970, at 0935, the steam tank...",3
3401,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,53° 30.00′ North,3° 20.00′ East,Unknown/Not applicable,Oil,No. 6 Fuel Oil,Unknown/Not applicable,Collision,"[ Early on the morning of April 30, 1969, the ...",168
3402,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,34° 10.00′ North,119° 45.00′ West,Unknown/Not applicable,Oil,California crude oil,Unknown/Not applicable,Wellhead,"[ On January 28, 1969, the Union Oil Company w...",4
3403,Unknown/Not applicable,NaN,Unknown/Not applicable,Applied,9° 35.00′ North,80° 40.00′ West,Unknown/Not applicable,Oil,Diesel,Unknown/Not applicable,Collision,"[ On December 13, 1968, the oil tanker Witwate...",588
3404,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,29° 38.00′ South,32° 15.00′ East,Unknown/Not applicable,NaN,Kuwait crude oil,Unknown/Not applicable,NaN,"[ At 1500 on June 13, 1968, the World Glory, ...",14
3405,Unknown/Not applicable,NaN,Applied,Applied,25° 20.00′ North,76° 20.00′ West,Unknown/Not applicable,NaN,Venezuelan crude oil,Unknown/Not applicable,NaN,"[ On March 7, 1968, the Greek tank vessel Gene...",1
3406,Unknown/Not applicable,NaN,Applied,Unknown/Not applicable,18° 29.00′ North,66° 10.00′ West,Unknown/Not applicable,NaN,Venezuelan light crude oil,Unknown/Not applicable,NaN,"[ On the morning of March 3, 1968, the tanker ...",2
3407,Unknown/Not applicable,NaN,Applied,Applied,50° 3.00′ North,4° 44.00′ West,Unknown/Not applicable,NaN,Kuwait crude oil,Unknown/Not applicable,NaN,"[ On the morning of March 18, 1967, the T/V To...",36
3408,NaN,NaN,NaN,NaN,31° 20.00′ North,116° 28.02′ West,NaN,NaN,diesel oil - approx. 80% heavy distillate,NaN,NaN,[ The Tampico Maru (henceforth Tampico) left ...,NaN

In [202]:
df.columns

Index(['Bioremediation', 'Cargo', 'Dispersants', 'In-Situ Burn',
       'Latitude (approximate)', 'Longitude (approximate)',
       'On-Water Recovery', 'Primary threat', 'Products of concern',
       'Shoreline Cleanup', 'Tags', 'Total amount at risk of spill'],
      dtype='object')

In [308]:
states.pop(2266)

[]

In [309]:
len(states)

3409

In [311]:
dates.pop(2266)

['1996-Sep-27']

In [312]:

len(dates)

3409

In [328]:
df['Text'] = states

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [313]:
df['Date'] = dates

In [329]:
df = df[['Longitude (approximate)', 'Latitude (approximate)', 'Total amount at risk of spill','Text', 'Date']]

In [330]:
df.shape

(3409, 5)

In [331]:
df

,Longitude (approximate),Latitude (approximate),Total amount at risk of spill,Text,Date
0,89° 17.55′ West,29° 19.08′ North,1 barrels,[LA],[2017-Sep-23]
1,89° 14.58′ West,29° 16.52′ North,5 barrels,[LA],[2017-Sep-22]
2,122° 19.53′ West,37° 48.64′ North,NaN,[CA],[2017-Sep-22]
3,95° 5.25′ West,29° 49.83′ North,4500 barrels,[TX],[2017-Sep-21]
4,69° 19.80′ West,43° 24.00′ North,NaN,[],[2017-Sep-19]
5,92° 7.68′ West,28° 14.50′ North,unknown gallons,[],[2017-Sep-19]
6,89° 29.74′ West,29° 39.94′ North,10 gallons,[],[2017-Sep-19]
7,93° 58.02′ West,29° 51.94′ North,unknown gallons,[TX],[2017-Sep-19]
8,162° 30.86′ West,54° 22.48′ North,550 gallons,[],[2017-Sep-07]
9,93° 22.12′ West,30° 3.56′ North,3500 gallons,"[WW, MM, LA]",[2017-Sep-05]
10,89° 19.50′ West,29° 33.47′ North,235 barrels,[],[2017-Aug-27]
11,87° 30.34′ West,41° 43.86′ North,NaN,[IL],[2017-Aug-25]
12,157° 11.40′ West,21° 22.20′ North,5000 gallons,[HI],[2017-Aug-25]
13,95° 36.60′ West,27° 47.40′ North,NaN,[],[2017-Aug-24]
14,122° 43.80′ West,48° 28.98′ North,NaN,[],[2017-Aug-24]
15,89° 21.48′ West,29° 15.07′ North,2300 gallons,[LA],[2017-Aug-23]
16,71° 0.73′ West,40° 39.16′ North,NaN,[],[2017-Aug-15]
17,94° 6.30′ West,27° 45.62′ North,unknown gallons,[],[2017-Aug-14]
18,166° 35.59′ West,53° 50.39′ North,30000 gallons,[],[2017-Aug-13]
19,147° 35.10′ West,60° 57.01′ North,1000 gallons,[],[2017-Aug-10]
20,84° 18.10′ West,46° 29.33′ North,105000 gallons,[MI],[2017-Aug-10]
21,135° 36.22′ West,57° 17.28′ North,600 gallons,[],[2017-Aug-09]
22,88° 58.20′ West,28° 56.15′ North,NaN,[],[2017-Aug-08]
23,118° 12.12′ West,33° 44.62′ North,6600 gallons,[CA],[2017-Aug-06]
24,88° 55.68′ West,28° 59.25′ North,NaN,[],[2017-Aug-05]
25,147° 45.16′ West,60° 9.41′ North,400 gallons,[],[2017-Aug-04]
26,89° 11.80′ West,30° 14.70′ North,2500 tons,[],[2017-Aug-03]
27,148° 31.09′ West,70° 23.13′ North,unkown gallons,[],[2017-Aug-01]
28,159° 59.34′ East,19° 6.64′ North,NaN,[],[2017-Jul-31]
29,153° 24.66′ West,58° 3.37′ North,700 gallons,[],[2017-Jul-24]
...,...,...,...,...,...
3379,8° 23.00′ West,43° 22.00′ North,9,[],[1976-May-12]
3380,79° 30.00′ West,1° 30.00′ North,NaN,[],[1976-Feb-05]
3381,76° 11.00′ West,37° 49.00′ North,250,[],[1976-Feb-02]
3382,66° 8.00′ West,18° 28.00′ North,323,[],[1975-Dec-09]
3383,1° 35.00′ West,50° 59.00′ North,588,[],[1975-Nov-12]
3384,93° 3.00′ West,28° 20.00′ North,294,[],[1975-Aug-15]
3385,43° 10.00′ West,22° 54.00′ South,NaN,[],[1975-Mar-26]
3386,75° 25.00′ West,39° 49.00′ North,84,[],[1975-Jan-31]
3387,8° 50.00′ West,41° 9.00′ North,NaN,[],[1975-Jan-29]
3388,69° 41.00′ West,52° 34.00′ South,NaN,[],[1974-Aug-09]
3389,62° 0.00′ West,10° 30.00′ North,NaN,[],[1973-Aug-08]
3390,67° 15.00′ West,18° 0.00′ North,1,[],[1973-Mar-18]
3391,94° 58.00′ West,29° 38.00′ North,420,[],[1973-Mar-09]
3392,57° 34.00′ East,25° 18.00′ North,NaN,[],[1972-Dec-19]
3393,70° 10.00′ West,43° 40.00′ North,100,[],[1972-Jul-22]
3394,75° 38.00′ West,40° 15.00′ North,7,[],[1972-Jun-22]
3395,20° 2.00′ East,35° 0.00′ South,NaN,[],[1971-Feb-27]
3396,122° 30.00′ West,37° 49.00′ North,NaN,[],[1971-Jan-18]
3397,90° 10.00′ West,28° 46.00′ North,NaN,[],[1970-Dec-01]
3398,1° 20.00′ West,50° 35.00′ North,1,[],[1970-Oct-23]
3399,88° 59.00′ West,29° 23.00′ North,NaN,[],[1970-Feb-10]
3400,61° 6.00′ West,45° 28.00′ North,3,[],[1970-Feb-04]
3401,3° 20.00′ East,53° 30.00′ North,168,[],[1969-Apr-30]
3402,119° 45.00′ West,34° 10.00′ North,4,[],[1969-Jan-28]
3403,80° 40.00′ West,9° 35.00′ North,588,[],[1968-Dec-13]
3404,32° 15.00′ East,29° 38.00′ South,14,[NE],[1968-Jun-13]
3405,76° 20.00′ West,25° 20.00′ North,1,[],[1968-Mar-07]
3406,66° 10.00′ West,18° 29.00′ North,2,[],[1968-Mar-03]
3407,4° 44.00′ West,50° 3.00′ North,36,[],[1967-Mar-18]
3408,116° 28.02′ West,31° 20.00′ North,NaN,[],[1957-Mar-29]

In [342]:
df.columns = ['Longitude', 'Latitude', 'Loss Estimated (Gallons|Barrels|Pounds)', 'Text', 'Date']

In [343]:
column_names = [i for i in df.columns.values]
for column in column_names:
    df[column] = df[column].apply(lambda x: str(x).replace("[","").replace("]","").replace('\'',""))

In [344]:
df

,Longitude,Latitude,Loss Estimated (Gallons|Barrels|Pounds),Text,Date
0,89° 17.55′ West,29° 19.08′ North,1 barrels,LA,2017-Sep-23
1,89° 14.58′ West,29° 16.52′ North,5 barrels,LA,2017-Sep-22
2,122° 19.53′ West,37° 48.64′ North,nan,CA,2017-Sep-22
3,95° 5.25′ West,29° 49.83′ North,4500 barrels,TX,2017-Sep-21
4,69° 19.80′ West,43° 24.00′ North,nan,,2017-Sep-19
5,92° 7.68′ West,28° 14.50′ North,unknown gallons,,2017-Sep-19
6,89° 29.74′ West,29° 39.94′ North,10 gallons,,2017-Sep-19
7,93° 58.02′ West,29° 51.94′ North,unknown gallons,TX,2017-Sep-19
8,162° 30.86′ West,54° 22.48′ North,550 gallons,,2017-Sep-07
9,93° 22.12′ West,30° 3.56′ North,3500 gallons,"WW, MM, LA",2017-Sep-05
10,89° 19.50′ West,29° 33.47′ North,235 barrels,,2017-Aug-27
11,87° 30.34′ West,41° 43.86′ North,nan,IL,2017-Aug-25
12,157° 11.40′ West,21° 22.20′ North,5000 gallons,HI,2017-Aug-25
13,95° 36.60′ West,27° 47.40′ North,nan,,2017-Aug-24
14,122° 43.80′ West,48° 28.98′ North,nan,,2017-Aug-24
15,89° 21.48′ West,29° 15.07′ North,2300 gallons,LA,2017-Aug-23
16,71° 0.73′ West,40° 39.16′ North,nan,,2017-Aug-15
17,94° 6.30′ West,27° 45.62′ North,unknown gallons,,2017-Aug-14
18,166° 35.59′ West,53° 50.39′ North,30000 gallons,,2017-Aug-13
19,147° 35.10′ West,60° 57.01′ North,1000 gallons,,2017-Aug-10
20,84° 18.10′ West,46° 29.33′ North,105000 gallons,MI,2017-Aug-10
21,135° 36.22′ West,57° 17.28′ North,600 gallons,,2017-Aug-09
22,88° 58.20′ West,28° 56.15′ North,nan,,2017-Aug-08
23,118° 12.12′ West,33° 44.62′ North,6600 gallons,CA,2017-Aug-06
24,88° 55.68′ West,28° 59.25′ North,nan,,2017-Aug-05
25,147° 45.16′ West,60° 9.41′ North,400 gallons,,2017-Aug-04
26,89° 11.80′ West,30° 14.70′ North,2500 tons,,2017-Aug-03
27,148° 31.09′ West,70° 23.13′ North,unkown gallons,,2017-Aug-01
28,159° 59.34′ East,19° 6.64′ North,nan,,2017-Jul-31
29,153° 24.66′ West,58° 3.37′ North,700 gallons,,2017-Jul-24
...,...,...,...,...,...
3379,8° 23.00′ West,43° 22.00′ North,9,,1976-May-12
3380,79° 30.00′ West,1° 30.00′ North,nan,,1976-Feb-05
3381,76° 11.00′ West,37° 49.00′ North,250,,1976-Feb-02
3382,66° 8.00′ West,18° 28.00′ North,323,,1975-Dec-09
3383,1° 35.00′ West,50° 59.00′ North,588,,1975-Nov-12
3384,93° 3.00′ West,28° 20.00′ North,294,,1975-Aug-15
3385,43° 10.00′ West,22° 54.00′ South,nan,,1975-Mar-26
3386,75° 25.00′ West,39° 49.00′ North,84,,1975-Jan-31
3387,8° 50.00′ West,41° 9.00′ North,nan,,1975-Jan-29
3388,69° 41.00′ West,52° 34.00′ South,nan,,1974-Aug-09
3389,62° 0.00′ West,10° 30.00′ North,nan,,1973-Aug-08
3390,67° 15.00′ West,18° 0.00′ North,1,,1973-Mar-18
3391,94° 58.00′ West,29° 38.00′ North,420,,1973-Mar-09
3392,57° 34.00′ East,25° 18.00′ North,nan,,1972-Dec-19
3393,70° 10.00′ West,43° 40.00′ North,100,,1972-Jul-22
3394,75° 38.00′ West,40° 15.00′ North,7,,1972-Jun-22
3395,20° 2.00′ East,35° 0.00′ South,nan,,1971-Feb-27
3396,122° 30.00′ West,37° 49.00′ North,nan,,1971-Jan-18
3397,90° 10.00′ West,28° 46.00′ North,nan,,1970-Dec-01
3398,1° 20.00′ West,50° 35.00′ North,1,,1970-Oct-23
3399,88° 59.00′ West,29° 23.00′ North,nan,,1970-Feb-10
3400,61° 6.00′ West,45° 28.00′ North,3,,1970-Feb-04
3401,3° 20.00′ East,53° 30.00′ North,168,,1969-Apr-30
3402,119° 45.00′ West,34° 10.00′ North,4,,1969-Jan-28
3403,80° 40.00′ West,9° 35.00′ North,588,,1968-Dec-13
3404,32° 15.00′ East,29° 38.00′ South,14,NE,1968-Jun-13
3405,76° 20.00′ West,25° 20.00′ North,1,,1968-Mar-07
3406,66° 10.00′ West,18° 29.00′ North,2,,1968-Mar-03
3407,4° 44.00′ West,50° 3.00′ North,36,,1967-Mar-18
3408,116° 28.02′ West,31° 20.00′ North,nan,,1957-Mar-29

In [345]:
writer = pd.ExcelWriter("incident_news_with_all_metrics.xlsx")
df.to_excel(writer,'incident_news_with_allmetrics')
writer.save()