In [1]:
import pandas as pd
import numpy as np
import re
import pycountry
from textblob import TextBlob
from calendar import month_name
from collections import Counter

In [94]:
file = 'nuclear_indcident_1952_2011.xlsx'
data = pd.read_excel(file)

In [95]:
# df = pd.DataFrame(data=data, columns=['Year', 'Cause of Loss', 'Deaths', 'Loss Estimated ($)', 'Location', 'Text'])
df = pd.DataFrame(data=data)
df

,Date,Location,Text,Deaths,Loss estimated ($ millions)
0,2011-09-12,"Marcoule, France","One person was killed and four injured, one se...",1,NaN
1,2011-03-12,"Fukushima, Japan",A tsunami flooded and damaged the plant's 5 ac...,2+,NaN
2,2006-07-25,"Forsmark, Sweden",An electrical fault at Forsmark Nuclear Power ...,0,100
3,2004-08-09,"Fukui Prefecture, Japan",Steam explosion at Mihama Nuclear Power Plant ...,4,9
4,2002-02-16,"Oak Harbor, Ohio, United States",Severe corrosion of control rod forces 24-mont...,0,143
5,1999-09-30,"Ibaraki Prefecture, Japan","Tokaimura nuclear accident killed two workers,...",2,54
6,1996-09-02,"Crystal River, Florida, United States",Balance-of-plant equipment malfunction forces ...,0,384
7,1996-02-20,"Waterford, Connecticut, United States",Leaking valve forces shutdown Millstone Nuclea...,0,254
8,1992-03-01,"Sosnovyi Bor, Leningrad Oblast, Russia",An accident at the Sosnovy Bor nuclear plant l...,NaN,NaN
9,1989-03-17,"Lusby, Maryland, United States",Inspections at Calvert Cliff Units 1 and 2 rev...,0,120
10,1987-12-19,"Lycoming, New York, United States",Malfunctions force Niagara Mohawk Power Corpor...,0,150
11,1987-03-31,"Delta, Pennsylvania, United States",Peach Bottom units 2 and 3 shutdown due to coo...,0,400
12,1986-05-04,"Hamm-Uentrop, West Germany",Experimental THTR-300 reactor releases small a...,0,267
13,1986-04-26,"Chernobyl, Chernobyl Raion (Now Ivankiv Raion)...","Overheating, steam explosion, fire, and meltdo...","30 direct, 19 not entirely related and 15 mino...",6700
14,1986-04-11,"Plymouth, Massachusetts, United States",Recurring equipment problems force emergency s...,0,1001
15,1985-03-09,"Athens, Alabama, United States",Instrumentation systems malfunction during sta...,0,1830
16,1984-09-15,"Athens, Alabama, United States","Safety violations, operator error, and design ...",0,110
17,1979-03-28,"Three Mile Island, Pennsylvania, United States",Loss of coolant and partial core meltdown due ...,0,2400
18,1977-02-22,"Jaslovské Bohunice, Czechoslovakia",Severe corrosion of reactor and release of rad...,0,1700
19,1976-01-05,"Jaslovské Bohunice, Czechoslovakia",Malfunction during fuel replacement. Fuel rod ...,2,NaN
20,1975-12-07,"Greifswald, East Germany",Electrical error causes fire in the main troug...,0,443
21,1905-05-28,"Sosnovyi Bor, Leningrad Oblast, Russia",There was reportedly a partial nuclear meltdow...,NaN,NaN
22,1969-01-21,"Lucens reactor, Vaud, Switzerland","On January 21, 1969, it suffered a loss-of-coo...",0,NaN
23,1966-10-05,"Frenchtown Charter Township, Michigan, United ...",Partial core meltdown of the Fermi 1 Reactor a...,0,132[24]
24,1961-01-03,"Idaho Falls, Idaho, United States",Explosion at SL-1 prototype at the National Re...,3,22
25,1957-10-10,"Sellafield aka Windscale fire, Cumberland, Uni...",A fire at the British atomic bomb project dest...,0,NaN
26,1957-09-29,"Mayak, Kyshtym, Russia",The Kyshtym disaster was a radiation contamina...,NaN,NaN
27,1957-07-26,"Simi Valley, California, United States",Partial core meltdown at Santa Susana Field La...,0,32

In [96]:
df.Location = df.Location.apply(lambda x: str(x).replace(',\xa0','-'))

In [97]:
df.Location = df.Location.apply(lambda x: re.sub(r'[A-Z]\w+\s?\w+[\s,]',"", str(x)))

In [98]:
df.Location[4]

' Ohio-States'

In [100]:
df.head(10)

,Date,Location,Text,Deaths,Loss estimated ($ millions)
0,2011-09-12,Marcoule-France,"One person was killed and four injured, one se...",1,NaN
1,2011-03-12,Fukushima-Japan,A tsunami flooded and damaged the plant's 5 ac...,2+,NaN
2,2006-07-25,Forsmark-Sweden,An electrical fault at Forsmark Nuclear Power ...,0,100
3,2004-08-09,Prefecture-Japan,Steam explosion at Mihama Nuclear Power Plant ...,4,9
4,2002-02-16,Ohio-States,Severe corrosion of control rod forces 24-mont...,0,143
5,1999-09-30,Prefecture-Japan,"Tokaimura nuclear accident killed two workers,...",2,54
6,1996-09-02,River-Florida-States,Balance-of-plant equipment malfunction forces ...,0,384
7,1996-02-20,Waterford-Connecticut-States,Leaking valve forces shutdown Millstone Nuclea...,0,254
8,1992-03-01,Bor-Oblast-Russia,An accident at the Sosnovy Bor nuclear plant l...,NaN,NaN
9,1989-03-17,Lusby-Maryland-States,Inspections at Calvert Cliff Units 1 and 2 rev...,0,120

In [107]:
df['Country'] = df.Location.apply(lambda x: re.findall(r'(?<=\-)\w+$', str(x)))
df['Country'] = df.Country.apply(lambda x: re.sub(r'\[|\]|\'', "", str(x)))

In [109]:
df.head(10)

,Date,Location,Text,Deaths,Loss estimated ($ millions),Country
0,2011-09-12,Marcoule-France,"One person was killed and four injured, one se...",1,NaN,France
1,2011-03-12,Fukushima-Japan,A tsunami flooded and damaged the plant's 5 ac...,2+,NaN,Japan
2,2006-07-25,Forsmark-Sweden,An electrical fault at Forsmark Nuclear Power ...,0,100,Sweden
3,2004-08-09,Prefecture-Japan,Steam explosion at Mihama Nuclear Power Plant ...,4,9,Japan
4,2002-02-16,Ohio-States,Severe corrosion of control rod forces 24-mont...,0,143,States
5,1999-09-30,Prefecture-Japan,"Tokaimura nuclear accident killed two workers,...",2,54,Japan
6,1996-09-02,River-Florida-States,Balance-of-plant equipment malfunction forces ...,0,384,States
7,1996-02-20,Waterford-Connecticut-States,Leaking valve forces shutdown Millstone Nuclea...,0,254,States
8,1992-03-01,Bor-Oblast-Russia,An accident at the Sosnovy Bor nuclear plant l...,NaN,NaN,Russia
9,1989-03-17,Lusby-Maryland-States,Inspections at Calvert Cliff Units 1 and 2 rev...,0,120,States

In [114]:
df['States'] = df.Location.apply(lambda x: re.findall(r'(?=\w+\-)\w+', str(x)))
df['States'] = df.States.apply(lambda x: re.sub(r'\[|\]|\'|,', "", str(x)))

In [115]:
df

,Date,Location,Text,Deaths,Loss estimated ($ millions),Country,States
0,2011-09-12,Marcoule-France,"One person was killed and four injured, one se...",1,NaN,France,Marcoule
1,2011-03-12,Fukushima-Japan,A tsunami flooded and damaged the plant's 5 ac...,2+,NaN,Japan,Fukushima
2,2006-07-25,Forsmark-Sweden,An electrical fault at Forsmark Nuclear Power ...,0,100,Sweden,Forsmark
3,2004-08-09,Prefecture-Japan,Steam explosion at Mihama Nuclear Power Plant ...,4,9,Japan,Prefecture
4,2002-02-16,Ohio-States,Severe corrosion of control rod forces 24-mont...,0,143,States,Ohio
5,1999-09-30,Prefecture-Japan,"Tokaimura nuclear accident killed two workers,...",2,54,Japan,Prefecture
6,1996-09-02,River-Florida-States,Balance-of-plant equipment malfunction forces ...,0,384,States,River Florida
7,1996-02-20,Waterford-Connecticut-States,Leaking valve forces shutdown Millstone Nuclea...,0,254,States,Waterford Connecticut
8,1992-03-01,Bor-Oblast-Russia,An accident at the Sosnovy Bor nuclear plant l...,NaN,NaN,Russia,Bor Oblast
9,1989-03-17,Lusby-Maryland-States,Inspections at Calvert Cliff Units 1 and 2 rev...,0,120,States,Lusby Maryland
10,1987-12-19,Lycoming-York-States,Malfunctions force Niagara Mohawk Power Corpor...,0,150,States,Lycoming York
11,1987-03-31,Delta-Pennsylvania-States,Peach Bottom units 2 and 3 shutdown due to coo...,0,400,States,Delta Pennsylvania
12,1986-05-04,Hamm-Uentrop-Germany,Experimental THTR-300 reactor releases small a...,0,267,Germany,Hamm Uentrop
13,1986-04-26,Chernobyl-(Raion)-Oblast-SSR,"Overheating, steam explosion, fire, and meltdo...","30 direct, 19 not entirely related and 15 mino...",6700,SSR,Chernobyl Oblast
14,1986-04-11,Plymouth-Massachusetts-States,Recurring equipment problems force emergency s...,0,1001,States,Plymouth Massachusetts
15,1985-03-09,Athens-Alabama-States,Instrumentation systems malfunction during sta...,0,1830,States,Athens Alabama
16,1984-09-15,Athens-Alabama-States,"Safety violations, operator error, and design ...",0,110,States,Athens Alabama
17,1979-03-28,Island-Pennsylvania-States,Loss of coolant and partial core meltdown due ...,0,2400,States,Island Pennsylvania
18,1977-02-22,Bohunice-Czechoslovakia,Severe corrosion of reactor and release of rad...,0,1700,Czechoslovakia,Bohunice
19,1976-01-05,Bohunice-Czechoslovakia,Malfunction during fuel replacement. Fuel rod ...,2,NaN,Czechoslovakia,Bohunice
20,1975-12-07,Greifswald-Germany,Electrical error causes fire in the main troug...,0,443,Germany,Greifswald
21,1905-05-28,Bor-Oblast-Russia,There was reportedly a partial nuclear meltdow...,NaN,NaN,Russia,Bor Oblast
22,1969-01-21,reactor-Vaud-Switzerland,"On January 21, 1969, it suffered a loss-of-coo...",0,NaN,Switzerland,reactor Vaud
23,1966-10-05,Township-Michigan-States,Partial core meltdown of the Fermi 1 Reactor a...,0,132[24],States,Township Michigan
24,1961-01-03,Falls-Idaho-States,Explosion at SL-1 prototype at the National Re...,3,22,States,Falls Idaho
25,1957-10-10,fire-Cumberland-Kingdom,A fire at the British atomic bomb project dest...,0,NaN,Kingdom,fire Cumberland
26,1957-09-29,Mayak-Kyshtym-Russia,The Kyshtym disaster was a radiation contamina...,NaN,NaN,Russia,Mayak Kyshtym
27,1957-07-26,Valley-California-States,Partial core meltdown at Santa Susana Field La...,0,32,States,Valley California

In [118]:
df = pd.DataFrame(data=df, columns=['Date','Country','States','Deaths','Loss estimated ($ millions)', 'Text'])

In [120]:
df.sort_values(['Date'], inplace=True)

In [121]:
df

,Date,Country,States,Deaths,Loss estimated ($ millions),Text
21,1905-05-28,Russia,Bor Oblast,NaN,NaN,There was reportedly a partial nuclear meltdow...
27,1957-07-26,States,Valley California,0,32,Partial core meltdown at Santa Susana Field La...
26,1957-09-29,Russia,Mayak Kyshtym,NaN,NaN,The Kyshtym disaster was a radiation contamina...
25,1957-10-10,Kingdom,fire Cumberland,0,NaN,A fire at the British atomic bomb project dest...
24,1961-01-03,States,Falls Idaho,3,22,Explosion at SL-1 prototype at the National Re...
23,1966-10-05,States,Township Michigan,0,132[24],Partial core meltdown of the Fermi 1 Reactor a...
22,1969-01-21,Switzerland,reactor Vaud,0,NaN,"On January 21, 1969, it suffered a loss-of-coo..."
20,1975-12-07,Germany,Greifswald,0,443,Electrical error causes fire in the main troug...
19,1976-01-05,Czechoslovakia,Bohunice,2,NaN,Malfunction during fuel replacement. Fuel rod ...
18,1977-02-22,Czechoslovakia,Bohunice,0,1700,Severe corrosion of reactor and release of rad...
17,1979-03-28,States,Island Pennsylvania,0,2400,Loss of coolant and partial core meltdown due ...
16,1984-09-15,States,Athens Alabama,0,110,"Safety violations, operator error, and design ..."
15,1985-03-09,States,Athens Alabama,0,1830,Instrumentation systems malfunction during sta...
14,1986-04-11,States,Plymouth Massachusetts,0,1001,Recurring equipment problems force emergency s...
13,1986-04-26,SSR,Chernobyl Oblast,"30 direct, 19 not entirely related and 15 mino...",6700,"Overheating, steam explosion, fire, and meltdo..."
12,1986-05-04,Germany,Hamm Uentrop,0,267,Experimental THTR-300 reactor releases small a...
11,1987-03-31,States,Delta Pennsylvania,0,400,Peach Bottom units 2 and 3 shutdown due to coo...
10,1987-12-19,States,Lycoming York,0,150,Malfunctions force Niagara Mohawk Power Corpor...
9,1989-03-17,States,Lusby Maryland,0,120,Inspections at Calvert Cliff Units 1 and 2 rev...
8,1992-03-01,Russia,Bor Oblast,NaN,NaN,An accident at the Sosnovy Bor nuclear plant l...
7,1996-02-20,States,Waterford Connecticut,0,254,Leaking valve forces shutdown Millstone Nuclea...
6,1996-09-02,States,River Florida,0,384,Balance-of-plant equipment malfunction forces ...
5,1999-09-30,Japan,Prefecture,2,54,"Tokaimura nuclear accident killed two workers,..."
4,2002-02-16,States,Ohio,0,143,Severe corrosion of control rod forces 24-mont...
3,2004-08-09,Japan,Prefecture,4,9,Steam explosion at Mihama Nuclear Power Plant ...
2,2006-07-25,Sweden,Forsmark,0,100,An electrical fault at Forsmark Nuclear Power ...
1,2011-03-12,Japan,Fukushima,2+,NaN,A tsunami flooded and damaged the plant's 5 ac...
0,2011-09-12,France,Marcoule,1,NaN,"One person was killed and four injured, one se..."

In [122]:
writer = pd.ExcelWriter('nuclear_indcident_1905_2011.xlsx')
df.to_excel(writer,'nuclear_indcident1905to2011')
writer.save()