In [1]:
import pandas as pd
import numpy as np
import re
import pycountry
from textblob import TextBlob
from calendar import month_name
from collections import Counter

In [2]:
file = 'nuclear_indcident_1952_2011.xlsx'
data = pd.read_excel(file)

In [3]:
# df = pd.DataFrame(data=data, columns=['Year', 'Cause of Loss', 'Deaths', 'Loss Estimated ($)', 'Location', 'Text'])
df = pd.DataFrame(data=data)
df

,Date,Location,Text,Deaths,Loss estimated ($ millions)
0,2011-09-12,"Marcoule, France","One person was killed and four injured, one se...",1,NaN
1,2011-03-12,"Fukushima, Japan",A tsunami flooded and damaged the plant's 5 ac...,2+,NaN
2,2006-07-25,"Forsmark, Sweden",An electrical fault at Forsmark Nuclear Power ...,0,100
3,2004-08-09,"Fukui Prefecture, Japan",Steam explosion at Mihama Nuclear Power Plant ...,4,9
4,2002-02-16,"Oak Harbor, Ohio, United States",Severe corrosion of control rod forces 24-mont...,0,143
5,1999-09-30,"Ibaraki Prefecture, Japan","Tokaimura nuclear accident killed two workers,...",2,54
6,1996-09-02,"Crystal River, Florida, United States",Balance-of-plant equipment malfunction forces ...,0,384
7,1996-02-20,"Waterford, Connecticut, United States",Leaking valve forces shutdown Millstone Nuclea...,0,254
8,1992-03-01,"Sosnovyi Bor, Leningrad Oblast, Russia",An accident at the Sosnovy Bor nuclear plant l...,NaN,NaN
9,1989-03-17,"Lusby, Maryland, United States",Inspections at Calvert Cliff Units 1 and 2 rev...,0,120
10,1987-12-19,"Lycoming, New York, United States",Malfunctions force Niagara Mohawk Power Corpor...,0,150
11,1987-03-31,"Delta, Pennsylvania, United States",Peach Bottom units 2 and 3 shutdown due to coo...,0,400
12,1986-05-04,"Hamm-Uentrop, West Germany",Experimental THTR-300 reactor releases small a...,0,267
13,1986-04-26,"Chernobyl, Chernobyl Raion (Now Ivankiv Raion)...","Overheating, steam explosion, fire, and meltdo...","30 direct, 19 not entirely related and 15 mino...",6700
14,1986-04-11,"Plymouth, Massachusetts, United States",Recurring equipment problems force emergency s...,0,1001
15,1985-03-09,"Athens, Alabama, United States",Instrumentation systems malfunction during sta...,0,1830
16,1984-09-15,"Athens, Alabama, United States","Safety violations, operator error, and design ...",0,110
17,1979-03-28,"Three Mile Island, Pennsylvania, United States",Loss of coolant and partial core meltdown due ...,0,2400
18,1977-02-22,"Jaslovské Bohunice, Czechoslovakia",Severe corrosion of reactor and release of rad...,0,1700
19,1976-01-05,"Jaslovské Bohunice, Czechoslovakia",Malfunction during fuel replacement. Fuel rod ...,2,NaN
20,1975-12-07,"Greifswald, East Germany",Electrical error causes fire in the main troug...,0,443
21,1905-05-28,"Sosnovyi Bor, Leningrad Oblast, Russia",There was reportedly a partial nuclear meltdow...,NaN,NaN
22,1969-01-21,"Lucens reactor, Vaud, Switzerland","On January 21, 1969, it suffered a loss-of-coo...",0,NaN
23,1966-10-05,"Frenchtown Charter Township, Michigan, United ...",Partial core meltdown of the Fermi 1 Reactor a...,0,132[24]
24,1961-01-03,"Idaho Falls, Idaho, United States",Explosion at SL-1 prototype at the National Re...,3,22
25,1957-10-10,"Sellafield aka Windscale fire, Cumberland, Uni...",A fire at the British atomic bomb project dest...,0,NaN
26,1957-09-29,"Mayak, Kyshtym, Russia",The Kyshtym disaster was a radiation contamina...,NaN,NaN
27,1957-07-26,"Simi Valley, California, United States",Partial core meltdown at Santa Susana Field La...,0,32

In [432]:
df.head()

,Year,Cause of Loss,Deaths,Loss Estimated (US$),Cause of Loss.1,Location,Text
0,1900,Tropical cyclone,"6,000 to 12,000","$28,000,000 (approximate)",1900 Galveston hurricane,Texas,Fatalities estimated. Remains the deadliest na...
1,1906,Earthquakeand fire (urban conflagration),"3,000+",NaN,1906 San Francisco earthquake,"San Francisco, California",Conflagration followed quake; fatalities estim...
2,2001,Terrorism,2996,178000000000,September 11 attacks,"New York City, Arlington County, Virginia, and...","2,977 victims and 19 hijackers. Costliest disa..."
4,1928,Tropical cyclone,2812,800000000,1928 Okeechobee hurricane,"Florida, Puerto Rico","4,078 believed dead total. 2500 in Florida, 31..."
6,1941,Military strike - bombing,2467,NaN,Attack on Pearl Harbor,"Honolulu, Hawaii","2,403 U.S. victims and 64 Japanese attackers."

In [433]:
df['Location'] =df['Location'].apply(lambda x: re.findall(r'\d.*0',str(x)))
df['Loss Estimated (US$)'] =df['Loss Estimated (US$)'].apply(lambda x: str(x).replace(',',"").replace('[',"")
                                                                             .replace(']', "")
                                                                             .replace('\'',""))
# df['Loss Estimated (US$)'] =df['Loss Estimated (US$)'].apply(lambda x: re.findall(r'^\[\d+0',str(x)))

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [434]:
df

,Year,Cause of Loss,Deaths,Loss Estimated (US$),Cause of Loss.1,Location,Text
0,1900,Tropical cyclone,"6,000 to 12,000",28000000,1900 Galveston hurricane,Texas,Fatalities estimated. Remains the deadliest na...
1,1906,Earthquakeand fire (urban conflagration),"3,000+",,1906 San Francisco earthquake,"San Francisco, California",Conflagration followed quake; fatalities estim...
2,2001,Terrorism,2996,178000000000,September 11 attacks,"New York City, Arlington County, Virginia, and...","2,977 victims and 19 hijackers. Costliest disa..."
4,1928,Tropical cyclone,2812,800000000,1928 Okeechobee hurricane,"Florida, Puerto Rico","4,078 believed dead total. 2500 in Florida, 31..."
6,1941,Military strike - bombing,2467,,Attack on Pearl Harbor,"Honolulu, Hawaii","2,403 U.S. victims and 64 Japanese attackers."
7,1889,Accident - Dam burst,2209,,Johnstown Flood,Pennsylvania,"Much rain, deforestation; dam failed"
8,1893,Tropical cyclone,2000,,1893 Cheniere Caminada hurricane,Louisiana,Fatalities estimated
9,2005,Tropical cyclone,1836,108000000000,Hurricane Katrina,"Florida, Louisiana, Mississippi, Alabama, Geor...",Costliest natural disaster in U.S. history.
10,1865,Accident - Shipwreck,1700,,Sultana,"Marion, Arkansas / Helena, Arkansas",Steamboat sank due to boiler explosion; fatali...
11,1980,Heat wave,1700,,1980 United States heat wave,Central and southern states,"Official death toll, may have been higher"
12,1871,Fire (rural),"1,500-2,500",,Peshtigo Fire,"Peshtigo, Wisconsin, Upper Peninsula of Michigan",Fatalities estimated; most deaths in single fi...
13,1904,Accident - Shipwreck,1021,,PS General Slocum,East River near New York City,Steamship sank due to fire on board
14,1893,Tropical cyclone,"1,000-2,000",,1893 Sea Islands hurricane,"Georgia, South Carolina",Fatalities estimated
15,1978,Mass murder - suicide,909,,Jonestown,"Georgetown, Guyana",Cult leader of the Peoples Temple Agricultural...
16,1945,Shipwreck,879,,USS Indianapolis[1],Philippine Sea,Largest loss of life in the history of the U.S...
17,1915,Accident - Shipwreck,844,,S.S. Eastland,"Chicago, Illinois","Passenger ship capsized in Chicago harbor, cau..."
18,1995,Heat wave,739,,Chicago Heat Wave of 1995,"Chicago, Illinois",NaN
19,1925,Tornado,695-747,1650000000,Tri-State Tornado,"Missouri, Illinois and Indiana(Kentucky, Tenne...",Lower number for single 3-state tornado; highe...
21,1903,Fire (building),602,,Iroquois Theatre fire,"Chicago, Illinois",Worst theater fire in American history; worst ...
22,1919,Tropical cyclone,600,,1919 Florida Keys hurricane,"Florida, Texas",NaN
23,1928,Accident - Dam failure,600,,St. Francis Dam,"Santa Clarita, California",NaN
24,1938,Tropical cyclone,600,,1938 New England hurricane,NaN,NaN
25,1947,Accident - Explosion,581,,Texas City disaster,"Texas City, Texas",Ammonium nitrate onboard ship
26,1871,Fire,500 (estimated),,Great Michigan Fire,Michigan,NaN
27,1942,Fire (building),492,,Cocoanut Grove fire,"Boston, Massachusetts",Nightclub fire; loss of life due to blocked ex...
28,1927,"Exploitation, Silicosis","476-1,000+",,Hawks Nest Tunnel disaster,"Gauley Bridge, West Virginia","178 admitted deaths, 476 with congressional in..."
29,1918,Fire (rural),453,7300000,1918 Cloquet fire,Minnesota,NaN
30,1936,Tornado outbreak,436+,,1936 Tupelo–Gainesville tornado outbreak,"Alabama, Arkansas, Mississippi, Georgia, South...","Two tornadoes in Tupelo, Mississippi, and Gain..."
31,1913,Flood,428,,1913 (Ohio) statewide flood,Ohio,NaN
32,1957,Tropical cyclone,416,147000000,Hurricane Audrey,"Louisiana, Texas, Mississippi, Alabama",NaN
...,...,...,...,...,...,...,...
342,1910,Bombing,21,,Los Angeles Timesbombing,"Los Angeles, California",NaN
343,1915,Fire(building),21,,St. Johns School fire,"Peabody, Massachusetts",Schoolgirls trapped behind exit door; resulted...
344,1919,Accident - Explosion,21,6600000000,Great Molasses Flood,"Boston, Massachusetts",Damages are out-of-court settlements only; rep...
346,1986,Accident - tour bus,21,,NaN,"Walker, California",NaN
347,1872,Fire (urban conflagration),20,73500000,Great Boston fire of 1872,"Boston, Massachusetts",NaN
349,1907,Accident - Railroad,20,,Woodlawn derailment,"Woodlawn, The Bronx, New York City",The day after the New York Central Railroad in...
350,2005,Accident - Shipwreck,20,,Ethan Allenboating accident,Lake George (New York),Overloaded tour boat capsized from another boa...
351,2010,Flood,20,,June 2010 Arkansas floods,"Albert Pike Recreation Area near Langley, Arka...",NaN
352,1897,Accident - Railroad,19,,Garrison train crash,"Garrison, New York",NaN
353,1944,Accident - Aircraft,19,,Long Creek air disaster,"South Portland, Maine",NaN
354,2013,Wildfire,19,,Yarnell Hill Fire,"Yarnell, Arizona",19 firefighters were killed trapped when they ...
355,1861,Accident - Railroad,17 to 20,,Platte Bridge Railroad Tragedy,"St. Joseph, Missouri",NaN
356,1903,Accident - Railroad,17,,Purdue Wreck,"Indianapolis, Indiana",NaN
357,2000,Terrorism,17,,USS Cole bombing,"Aden, Yemen",NaN
358,1965,Accidents - Pipeline accidents,17,,Pipeline explosion and fire,"Natchitoches, Louisiana",NaN
359,1966,Mass murder,17,,University of Texas massacre,"Austin, Texas",NaN
360,1991,Accident - Automobile,17,,Dust storm accident,"Coalinga, California",NaN
361,2002,Mass murder,17,,Beltway sniper attacks,Washington metropolitan area,3 injured in the Beltway sniper attacks and 7 ...
363,1926,Tornado,16,,La Plata tornado of 1926,"La Plata, Maryland",13 killed in La Plata Elementary School
364,1978,Accident - Railroad,16,,"Waverly, Tennessee, tank car explosion","Waverly, Tennessee",An additional 43 injured
365,1987,Accident - Railroad,16,,1987 Maryland train collision,"Chase, Maryland",NaN
366,1987,Mass Murder,16,,The Dover massacre,"Dover, Arkansas - Russellville, Arkansas",NaN
368,2015,Terrorism,16,,2015 San Bernardino attack,"San Bernardino, California",An additional 24 injured
369,2016,Accident - Hot air balloon,16,,2016 Lockhart hot air balloon crash,"Lockhart, Texas",Deadliest ballooning disaster in U.S. history
370,2017,blizzard,16-19,,March 2017 North American blizzard,"Northeastern United States, Upper Midwest, Gre...",NaN
371,1954,Fire(building),15,,Cleveland Hill Middle School fire,"Cheektowaga, New York",NaN
372,1986,Mass murder,15,,Edmond post office shooting,"Edmond, Oklahoma",14 victims and 1 perpetrator
373,1999,Mass murder,15,,Columbine High School massacre,"Jefferson County, Colorado","Armed with 2 sawed-off shotguns, a TEC-9 pisto..."
374,2011,Accident - tour bus,15,,World Wide Tours bus crash,"Bronx, New York","En route to Connecticut casino, March 12"
375,2013,Accident - Explosion,15,,West Fertilizer Company explosion,"West, Texas",More than 160 people were injured.

In [435]:
# df['Loss Estimated (US$)'] =df['Loss Estimated (US$)'].apply(lambda x: str(x).replace('[',"")
#                                                                              .replace(']', "")
#                                                                              .replace('\'',"").replace('(',""))
df['Loss Estimated (US$)'] =df['Loss Estimated (US$)'].apply(lambda x: re.findall(r'^\d+0',str(x)))
df['Loss Estimated (US$)'] =df['Loss Estimated (US$)'].apply(lambda x: str(x).replace(',',"").replace('[',"")
                                                                             .replace(']', "")
                                                                             .replace('\'',""))

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [436]:
df

,Year,Cause of Loss,Deaths,Loss Estimated (US$),Cause of Loss.1,Location,Text
0,1900,Tropical cyclone,"6,000 to 12,000",28000000,1900 Galveston hurricane,Texas,Fatalities estimated. Remains the deadliest na...
1,1906,Earthquakeand fire (urban conflagration),"3,000+",,1906 San Francisco earthquake,"San Francisco, California",Conflagration followed quake; fatalities estim...
2,2001,Terrorism,2996,178000000000,September 11 attacks,"New York City, Arlington County, Virginia, and...","2,977 victims and 19 hijackers. Costliest disa..."
4,1928,Tropical cyclone,2812,800000000,1928 Okeechobee hurricane,"Florida, Puerto Rico","4,078 believed dead total. 2500 in Florida, 31..."
6,1941,Military strike - bombing,2467,,Attack on Pearl Harbor,"Honolulu, Hawaii","2,403 U.S. victims and 64 Japanese attackers."
7,1889,Accident - Dam burst,2209,,Johnstown Flood,Pennsylvania,"Much rain, deforestation; dam failed"
8,1893,Tropical cyclone,2000,,1893 Cheniere Caminada hurricane,Louisiana,Fatalities estimated
9,2005,Tropical cyclone,1836,108000000000,Hurricane Katrina,"Florida, Louisiana, Mississippi, Alabama, Geor...",Costliest natural disaster in U.S. history.
10,1865,Accident - Shipwreck,1700,,Sultana,"Marion, Arkansas / Helena, Arkansas",Steamboat sank due to boiler explosion; fatali...
11,1980,Heat wave,1700,,1980 United States heat wave,Central and southern states,"Official death toll, may have been higher"
12,1871,Fire (rural),"1,500-2,500",,Peshtigo Fire,"Peshtigo, Wisconsin, Upper Peninsula of Michigan",Fatalities estimated; most deaths in single fi...
13,1904,Accident - Shipwreck,1021,,PS General Slocum,East River near New York City,Steamship sank due to fire on board
14,1893,Tropical cyclone,"1,000-2,000",,1893 Sea Islands hurricane,"Georgia, South Carolina",Fatalities estimated
15,1978,Mass murder - suicide,909,,Jonestown,"Georgetown, Guyana",Cult leader of the Peoples Temple Agricultural...
16,1945,Shipwreck,879,,USS Indianapolis[1],Philippine Sea,Largest loss of life in the history of the U.S...
17,1915,Accident - Shipwreck,844,,S.S. Eastland,"Chicago, Illinois","Passenger ship capsized in Chicago harbor, cau..."
18,1995,Heat wave,739,,Chicago Heat Wave of 1995,"Chicago, Illinois",NaN
19,1925,Tornado,695-747,1650000000,Tri-State Tornado,"Missouri, Illinois and Indiana(Kentucky, Tenne...",Lower number for single 3-state tornado; highe...
21,1903,Fire (building),602,,Iroquois Theatre fire,"Chicago, Illinois",Worst theater fire in American history; worst ...
22,1919,Tropical cyclone,600,,1919 Florida Keys hurricane,"Florida, Texas",NaN
23,1928,Accident - Dam failure,600,,St. Francis Dam,"Santa Clarita, California",NaN
24,1938,Tropical cyclone,600,,1938 New England hurricane,NaN,NaN
25,1947,Accident - Explosion,581,,Texas City disaster,"Texas City, Texas",Ammonium nitrate onboard ship
26,1871,Fire,500 (estimated),,Great Michigan Fire,Michigan,NaN
27,1942,Fire (building),492,,Cocoanut Grove fire,"Boston, Massachusetts",Nightclub fire; loss of life due to blocked ex...
28,1927,"Exploitation, Silicosis","476-1,000+",,Hawks Nest Tunnel disaster,"Gauley Bridge, West Virginia","178 admitted deaths, 476 with congressional in..."
29,1918,Fire (rural),453,7300000,1918 Cloquet fire,Minnesota,NaN
30,1936,Tornado outbreak,436+,,1936 Tupelo–Gainesville tornado outbreak,"Alabama, Arkansas, Mississippi, Georgia, South...","Two tornadoes in Tupelo, Mississippi, and Gain..."
31,1913,Flood,428,,1913 (Ohio) statewide flood,Ohio,NaN
32,1957,Tropical cyclone,416,147000000,Hurricane Audrey,"Louisiana, Texas, Mississippi, Alabama",NaN
...,...,...,...,...,...,...,...
342,1910,Bombing,21,,Los Angeles Timesbombing,"Los Angeles, California",NaN
343,1915,Fire(building),21,,St. Johns School fire,"Peabody, Massachusetts",Schoolgirls trapped behind exit door; resulted...
344,1919,Accident - Explosion,21,6600000000,Great Molasses Flood,"Boston, Massachusetts",Damages are out-of-court settlements only; rep...
346,1986,Accident - tour bus,21,,NaN,"Walker, California",NaN
347,1872,Fire (urban conflagration),20,73500000,Great Boston fire of 1872,"Boston, Massachusetts",NaN
349,1907,Accident - Railroad,20,,Woodlawn derailment,"Woodlawn, The Bronx, New York City",The day after the New York Central Railroad in...
350,2005,Accident - Shipwreck,20,,Ethan Allenboating accident,Lake George (New York),Overloaded tour boat capsized from another boa...
351,2010,Flood,20,,June 2010 Arkansas floods,"Albert Pike Recreation Area near Langley, Arka...",NaN
352,1897,Accident - Railroad,19,,Garrison train crash,"Garrison, New York",NaN
353,1944,Accident - Aircraft,19,,Long Creek air disaster,"South Portland, Maine",NaN
354,2013,Wildfire,19,,Yarnell Hill Fire,"Yarnell, Arizona",19 firefighters were killed trapped when they ...
355,1861,Accident - Railroad,17 to 20,,Platte Bridge Railroad Tragedy,"St. Joseph, Missouri",NaN
356,1903,Accident - Railroad,17,,Purdue Wreck,"Indianapolis, Indiana",NaN
357,2000,Terrorism,17,,USS Cole bombing,"Aden, Yemen",NaN
358,1965,Accidents - Pipeline accidents,17,,Pipeline explosion and fire,"Natchitoches, Louisiana",NaN
359,1966,Mass murder,17,,University of Texas massacre,"Austin, Texas",NaN
360,1991,Accident - Automobile,17,,Dust storm accident,"Coalinga, California",NaN
361,2002,Mass murder,17,,Beltway sniper attacks,Washington metropolitan area,3 injured in the Beltway sniper attacks and 7 ...
363,1926,Tornado,16,,La Plata tornado of 1926,"La Plata, Maryland",13 killed in La Plata Elementary School
364,1978,Accident - Railroad,16,,"Waverly, Tennessee, tank car explosion","Waverly, Tennessee",An additional 43 injured
365,1987,Accident - Railroad,16,,1987 Maryland train collision,"Chase, Maryland",NaN
366,1987,Mass Murder,16,,The Dover massacre,"Dover, Arkansas - Russellville, Arkansas",NaN
368,2015,Terrorism,16,,2015 San Bernardino attack,"San Bernardino, California",An additional 24 injured
369,2016,Accident - Hot air balloon,16,,2016 Lockhart hot air balloon crash,"Lockhart, Texas",Deadliest ballooning disaster in U.S. history
370,2017,blizzard,16-19,,March 2017 North American blizzard,"Northeastern United States, Upper Midwest, Gre...",NaN
371,1954,Fire(building),15,,Cleveland Hill Middle School fire,"Cheektowaga, New York",NaN
372,1986,Mass murder,15,,Edmond post office shooting,"Edmond, Oklahoma",14 victims and 1 perpetrator
373,1999,Mass murder,15,,Columbine High School massacre,"Jefferson County, Colorado","Armed with 2 sawed-off shotguns, a TEC-9 pisto..."
374,2011,Accident - tour bus,15,,World Wide Tours bus crash,"Bronx, New York","En route to Connecticut casino, March 12"
375,2013,Accident - Explosion,15,,West Fertilizer Company explosion,"West, Texas",More than 160 people were injured.

In [437]:
df['Loss Estimated (US$)'] = df['Loss Estimated (US$)'].apply(lambda x: int(x) if str(x) != '' else x)

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [438]:
# df['Loss Estimated (US$)'] =df['Loss Estimated (US$)'].apply(lambda x: str(x).replace('$',"")
#                                                                              .replace('(approximate)', "")
#                                                                              .replace(',',"").replace('<',"").replace('>',"")
#                                                                              .replace('-',"").replace('nan',"0").replace("~",""))
# df['Loss Estimated (US$)'] =df['Loss Estimated (US$)'].apply(lambda x: int(x))

In [439]:
df

,Year,Cause of Loss,Deaths,Loss Estimated (US$),Cause of Loss.1,Location,Text
0,1900,Tropical cyclone,"6,000 to 12,000",28000000,1900 Galveston hurricane,Texas,Fatalities estimated. Remains the deadliest na...
1,1906,Earthquakeand fire (urban conflagration),"3,000+",,1906 San Francisco earthquake,"San Francisco, California",Conflagration followed quake; fatalities estim...
2,2001,Terrorism,2996,178000000000,September 11 attacks,"New York City, Arlington County, Virginia, and...","2,977 victims and 19 hijackers. Costliest disa..."
4,1928,Tropical cyclone,2812,800000000,1928 Okeechobee hurricane,"Florida, Puerto Rico","4,078 believed dead total. 2500 in Florida, 31..."
6,1941,Military strike - bombing,2467,,Attack on Pearl Harbor,"Honolulu, Hawaii","2,403 U.S. victims and 64 Japanese attackers."
7,1889,Accident - Dam burst,2209,,Johnstown Flood,Pennsylvania,"Much rain, deforestation; dam failed"
8,1893,Tropical cyclone,2000,,1893 Cheniere Caminada hurricane,Louisiana,Fatalities estimated
9,2005,Tropical cyclone,1836,108000000000,Hurricane Katrina,"Florida, Louisiana, Mississippi, Alabama, Geor...",Costliest natural disaster in U.S. history.
10,1865,Accident - Shipwreck,1700,,Sultana,"Marion, Arkansas / Helena, Arkansas",Steamboat sank due to boiler explosion; fatali...
11,1980,Heat wave,1700,,1980 United States heat wave,Central and southern states,"Official death toll, may have been higher"
12,1871,Fire (rural),"1,500-2,500",,Peshtigo Fire,"Peshtigo, Wisconsin, Upper Peninsula of Michigan",Fatalities estimated; most deaths in single fi...
13,1904,Accident - Shipwreck,1021,,PS General Slocum,East River near New York City,Steamship sank due to fire on board
14,1893,Tropical cyclone,"1,000-2,000",,1893 Sea Islands hurricane,"Georgia, South Carolina",Fatalities estimated
15,1978,Mass murder - suicide,909,,Jonestown,"Georgetown, Guyana",Cult leader of the Peoples Temple Agricultural...
16,1945,Shipwreck,879,,USS Indianapolis[1],Philippine Sea,Largest loss of life in the history of the U.S...
17,1915,Accident - Shipwreck,844,,S.S. Eastland,"Chicago, Illinois","Passenger ship capsized in Chicago harbor, cau..."
18,1995,Heat wave,739,,Chicago Heat Wave of 1995,"Chicago, Illinois",NaN
19,1925,Tornado,695-747,1650000000,Tri-State Tornado,"Missouri, Illinois and Indiana(Kentucky, Tenne...",Lower number for single 3-state tornado; highe...
21,1903,Fire (building),602,,Iroquois Theatre fire,"Chicago, Illinois",Worst theater fire in American history; worst ...
22,1919,Tropical cyclone,600,,1919 Florida Keys hurricane,"Florida, Texas",NaN
23,1928,Accident - Dam failure,600,,St. Francis Dam,"Santa Clarita, California",NaN
24,1938,Tropical cyclone,600,,1938 New England hurricane,NaN,NaN
25,1947,Accident - Explosion,581,,Texas City disaster,"Texas City, Texas",Ammonium nitrate onboard ship
26,1871,Fire,500 (estimated),,Great Michigan Fire,Michigan,NaN
27,1942,Fire (building),492,,Cocoanut Grove fire,"Boston, Massachusetts",Nightclub fire; loss of life due to blocked ex...
28,1927,"Exploitation, Silicosis","476-1,000+",,Hawks Nest Tunnel disaster,"Gauley Bridge, West Virginia","178 admitted deaths, 476 with congressional in..."
29,1918,Fire (rural),453,7300000,1918 Cloquet fire,Minnesota,NaN
30,1936,Tornado outbreak,436+,,1936 Tupelo–Gainesville tornado outbreak,"Alabama, Arkansas, Mississippi, Georgia, South...","Two tornadoes in Tupelo, Mississippi, and Gain..."
31,1913,Flood,428,,1913 (Ohio) statewide flood,Ohio,NaN
32,1957,Tropical cyclone,416,147000000,Hurricane Audrey,"Louisiana, Texas, Mississippi, Alabama",NaN
...,...,...,...,...,...,...,...
342,1910,Bombing,21,,Los Angeles Timesbombing,"Los Angeles, California",NaN
343,1915,Fire(building),21,,St. Johns School fire,"Peabody, Massachusetts",Schoolgirls trapped behind exit door; resulted...
344,1919,Accident - Explosion,21,6600000000,Great Molasses Flood,"Boston, Massachusetts",Damages are out-of-court settlements only; rep...
346,1986,Accident - tour bus,21,,NaN,"Walker, California",NaN
347,1872,Fire (urban conflagration),20,73500000,Great Boston fire of 1872,"Boston, Massachusetts",NaN
349,1907,Accident - Railroad,20,,Woodlawn derailment,"Woodlawn, The Bronx, New York City",The day after the New York Central Railroad in...
350,2005,Accident - Shipwreck,20,,Ethan Allenboating accident,Lake George (New York),Overloaded tour boat capsized from another boa...
351,2010,Flood,20,,June 2010 Arkansas floods,"Albert Pike Recreation Area near Langley, Arka...",NaN
352,1897,Accident - Railroad,19,,Garrison train crash,"Garrison, New York",NaN
353,1944,Accident - Aircraft,19,,Long Creek air disaster,"South Portland, Maine",NaN
354,2013,Wildfire,19,,Yarnell Hill Fire,"Yarnell, Arizona",19 firefighters were killed trapped when they ...
355,1861,Accident - Railroad,17 to 20,,Platte Bridge Railroad Tragedy,"St. Joseph, Missouri",NaN
356,1903,Accident - Railroad,17,,Purdue Wreck,"Indianapolis, Indiana",NaN
357,2000,Terrorism,17,,USS Cole bombing,"Aden, Yemen",NaN
358,1965,Accidents - Pipeline accidents,17,,Pipeline explosion and fire,"Natchitoches, Louisiana",NaN
359,1966,Mass murder,17,,University of Texas massacre,"Austin, Texas",NaN
360,1991,Accident - Automobile,17,,Dust storm accident,"Coalinga, California",NaN
361,2002,Mass murder,17,,Beltway sniper attacks,Washington metropolitan area,3 injured in the Beltway sniper attacks and 7 ...
363,1926,Tornado,16,,La Plata tornado of 1926,"La Plata, Maryland",13 killed in La Plata Elementary School
364,1978,Accident - Railroad,16,,"Waverly, Tennessee, tank car explosion","Waverly, Tennessee",An additional 43 injured
365,1987,Accident - Railroad,16,,1987 Maryland train collision,"Chase, Maryland",NaN
366,1987,Mass Murder,16,,The Dover massacre,"Dover, Arkansas - Russellville, Arkansas",NaN
368,2015,Terrorism,16,,2015 San Bernardino attack,"San Bernardino, California",An additional 24 injured
369,2016,Accident - Hot air balloon,16,,2016 Lockhart hot air balloon crash,"Lockhart, Texas",Deadliest ballooning disaster in U.S. history
370,2017,blizzard,16-19,,March 2017 North American blizzard,"Northeastern United States, Upper Midwest, Gre...",NaN
371,1954,Fire(building),15,,Cleveland Hill Middle School fire,"Cheektowaga, New York",NaN
372,1986,Mass murder,15,,Edmond post office shooting,"Edmond, Oklahoma",14 victims and 1 perpetrator
373,1999,Mass murder,15,,Columbine High School massacre,"Jefferson County, Colorado","Armed with 2 sawed-off shotguns, a TEC-9 pisto..."
374,2011,Accident - tour bus,15,,World Wide Tours bus crash,"Bronx, New York","En route to Connecticut casino, March 12"
375,2013,Accident - Explosion,15,,West Fertilizer Company explosion,"West, Texas",More than 160 people were injured.

In [440]:
df['Location'] =df['Location'].apply(lambda x: re.sub(r'\(.*\)', "",str(x)))

# df['Location'] =df['Location'].apply(lambda x: re.findall(r'[A-Z]\w+?\s?\w+$',str(x)))
# df['Location'] =df['Location'].apply(lambda x: re.findall(r'[A-Z]?\w+?\s?[A-Z]?\w+$',str(x)))

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [441]:
df['Location'] =df['Location'].apply(lambda x: re.findall(r'[A-Z]?\w+?\s?\w+$',str(x)))
df['Location'] =df['Location'].apply(lambda x: str(x).replace('[',"").replace(']', "").replace("\'",""))

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [442]:
df

,Year,Cause of Loss,Deaths,Loss Estimated (US$),Cause of Loss.1,Location,Text
0,1900,Tropical cyclone,"6,000 to 12,000",28000000,1900 Galveston hurricane,Texas,Fatalities estimated. Remains the deadliest na...
1,1906,Earthquakeand fire (urban conflagration),"3,000+",,1906 San Francisco earthquake,California,Conflagration followed quake; fatalities estim...
2,2001,Terrorism,2996,178000000000,September 11 attacks,Pennsylvania,"2,977 victims and 19 hijackers. Costliest disa..."
4,1928,Tropical cyclone,2812,800000000,1928 Okeechobee hurricane,Puerto Rico,"4,078 believed dead total. 2500 in Florida, 31..."
6,1941,Military strike - bombing,2467,,Attack on Pearl Harbor,Hawaii,"2,403 U.S. victims and 64 Japanese attackers."
7,1889,Accident - Dam burst,2209,,Johnstown Flood,Pennsylvania,"Much rain, deforestation; dam failed"
8,1893,Tropical cyclone,2000,,1893 Cheniere Caminada hurricane,Louisiana,Fatalities estimated
9,2005,Tropical cyclone,1836,108000000000,Hurricane Katrina,and\xa0Ohio,Costliest natural disaster in U.S. history.
10,1865,Accident - Shipwreck,1700,,Sultana,Arkansas,Steamboat sank due to boiler explosion; fatali...
11,1980,Heat wave,1700,,1980 United States heat wave,southern states,"Official death toll, may have been higher"
12,1871,Fire (rural),"1,500-2,500",,Peshtigo Fire,of Michigan,Fatalities estimated; most deaths in single fi...
13,1904,Accident - Shipwreck,1021,,PS General Slocum,York City,Steamship sank due to fire on board
14,1893,Tropical cyclone,"1,000-2,000",,1893 Sea Islands hurricane,South Carolina,Fatalities estimated
15,1978,Mass murder - suicide,909,,Jonestown,Guyana,Cult leader of the Peoples Temple Agricultural...
16,1945,Shipwreck,879,,USS Indianapolis[1],Philippine Sea,Largest loss of life in the history of the U.S...
17,1915,Accident - Shipwreck,844,,S.S. Eastland,Illinois,"Passenger ship capsized in Chicago harbor, cau..."
18,1995,Heat wave,739,,Chicago Heat Wave of 1995,Illinois,NaN
19,1925,Tornado,695-747,1650000000,Tri-State Tornado,and\xa0Indiana,Lower number for single 3-state tornado; highe...
21,1903,Fire (building),602,,Iroquois Theatre fire,Illinois,Worst theater fire in American history; worst ...
22,1919,Tropical cyclone,600,,1919 Florida Keys hurricane,Texas,NaN
23,1928,Accident - Dam failure,600,,St. Francis Dam,California,NaN
24,1938,Tropical cyclone,600,,1938 New England hurricane,nan,NaN
25,1947,Accident - Explosion,581,,Texas City disaster,Texas,Ammonium nitrate onboard ship
26,1871,Fire,500 (estimated),,Great Michigan Fire,Michigan,NaN
27,1942,Fire (building),492,,Cocoanut Grove fire,Massachusetts,Nightclub fire; loss of life due to blocked ex...
28,1927,"Exploitation, Silicosis","476-1,000+",,Hawks Nest Tunnel disaster,West Virginia,"178 admitted deaths, 476 with congressional in..."
29,1918,Fire (rural),453,7300000,1918 Cloquet fire,Minnesota,NaN
30,1936,Tornado outbreak,436+,,1936 Tupelo–Gainesville tornado outbreak,Tennessee,"Two tornadoes in Tupelo, Mississippi, and Gain..."
31,1913,Flood,428,,1913 (Ohio) statewide flood,Ohio,NaN
32,1957,Tropical cyclone,416,147000000,Hurricane Audrey,Alabama,NaN
...,...,...,...,...,...,...,...
342,1910,Bombing,21,,Los Angeles Timesbombing,California,NaN
343,1915,Fire(building),21,,St. Johns School fire,Massachusetts,Schoolgirls trapped behind exit door; resulted...
344,1919,Accident - Explosion,21,6600000000,Great Molasses Flood,Massachusetts,Damages are out-of-court settlements only; rep...
346,1986,Accident - tour bus,21,,NaN,California,NaN
347,1872,Fire (urban conflagration),20,73500000,Great Boston fire of 1872,Massachusetts,NaN
349,1907,Accident - Railroad,20,,Woodlawn derailment,York City,The day after the New York Central Railroad in...
350,2005,Accident - Shipwreck,20,,Ethan Allenboating accident,,Overloaded tour boat capsized from another boa...
351,2010,Flood,20,,June 2010 Arkansas floods,Arkansas,NaN
352,1897,Accident - Railroad,19,,Garrison train crash,New York,NaN
353,1944,Accident - Aircraft,19,,Long Creek air disaster,Maine,NaN
354,2013,Wildfire,19,,Yarnell Hill Fire,Arizona,19 firefighters were killed trapped when they ...
355,1861,Accident - Railroad,17 to 20,,Platte Bridge Railroad Tragedy,Missouri,NaN
356,1903,Accident - Railroad,17,,Purdue Wreck,Indiana,NaN
357,2000,Terrorism,17,,USS Cole bombing,Yemen,NaN
358,1965,Accidents - Pipeline accidents,17,,Pipeline explosion and fire,Louisiana,NaN
359,1966,Mass murder,17,,University of Texas massacre,Texas,NaN
360,1991,Accident - Automobile,17,,Dust storm accident,California,NaN
361,2002,Mass murder,17,,Beltway sniper attacks,metropolitan area,3 injured in the Beltway sniper attacks and 7 ...
363,1926,Tornado,16,,La Plata tornado of 1926,Maryland,13 killed in La Plata Elementary School
364,1978,Accident - Railroad,16,,"Waverly, Tennessee, tank car explosion",Tennessee,An additional 43 injured
365,1987,Accident - Railroad,16,,1987 Maryland train collision,Maryland,NaN
366,1987,Mass Murder,16,,The Dover massacre,Arkansas,NaN
368,2015,Terrorism,16,,2015 San Bernardino attack,California,An additional 24 injured
369,2016,Accident - Hot air balloon,16,,2016 Lockhart hot air balloon crash,Texas,Deadliest ballooning disaster in U.S. history
370,2017,blizzard,16-19,,March 2017 North American blizzard,Great Plains,NaN
371,1954,Fire(building),15,,Cleveland Hill Middle School fire,New York,NaN
372,1986,Mass murder,15,,Edmond post office shooting,Oklahoma,14 victims and 1 perpetrator
373,1999,Mass murder,15,,Columbine High School massacre,Colorado,"Armed with 2 sawed-off shotguns, a TEC-9 pisto..."
374,2011,Accident - tour bus,15,,World Wide Tours bus crash,New York,"En route to Connecticut casino, March 12"
375,2013,Accident - Explosion,15,,West Fertilizer Company explosion,Texas,More than 160 people were injured.

In [443]:
df.drop(labels='Cause of Loss.1',axis=1, inplace=True)

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [444]:
df.insert(1, 'Country', value='USA')

In [445]:
df

,Year,Country,Cause of Loss,Deaths,Loss Estimated (US$),Location,Text
0,1900,USA,Tropical cyclone,"6,000 to 12,000",28000000,Texas,Fatalities estimated. Remains the deadliest na...
1,1906,USA,Earthquakeand fire (urban conflagration),"3,000+",,California,Conflagration followed quake; fatalities estim...
2,2001,USA,Terrorism,2996,178000000000,Pennsylvania,"2,977 victims and 19 hijackers. Costliest disa..."
4,1928,USA,Tropical cyclone,2812,800000000,Puerto Rico,"4,078 believed dead total. 2500 in Florida, 31..."
6,1941,USA,Military strike - bombing,2467,,Hawaii,"2,403 U.S. victims and 64 Japanese attackers."
7,1889,USA,Accident - Dam burst,2209,,Pennsylvania,"Much rain, deforestation; dam failed"
8,1893,USA,Tropical cyclone,2000,,Louisiana,Fatalities estimated
9,2005,USA,Tropical cyclone,1836,108000000000,and\xa0Ohio,Costliest natural disaster in U.S. history.
10,1865,USA,Accident - Shipwreck,1700,,Arkansas,Steamboat sank due to boiler explosion; fatali...
11,1980,USA,Heat wave,1700,,southern states,"Official death toll, may have been higher"
12,1871,USA,Fire (rural),"1,500-2,500",,of Michigan,Fatalities estimated; most deaths in single fi...
13,1904,USA,Accident - Shipwreck,1021,,York City,Steamship sank due to fire on board
14,1893,USA,Tropical cyclone,"1,000-2,000",,South Carolina,Fatalities estimated
15,1978,USA,Mass murder - suicide,909,,Guyana,Cult leader of the Peoples Temple Agricultural...
16,1945,USA,Shipwreck,879,,Philippine Sea,Largest loss of life in the history of the U.S...
17,1915,USA,Accident - Shipwreck,844,,Illinois,"Passenger ship capsized in Chicago harbor, cau..."
18,1995,USA,Heat wave,739,,Illinois,NaN
19,1925,USA,Tornado,695-747,1650000000,and\xa0Indiana,Lower number for single 3-state tornado; highe...
21,1903,USA,Fire (building),602,,Illinois,Worst theater fire in American history; worst ...
22,1919,USA,Tropical cyclone,600,,Texas,NaN
23,1928,USA,Accident - Dam failure,600,,California,NaN
24,1938,USA,Tropical cyclone,600,,nan,NaN
25,1947,USA,Accident - Explosion,581,,Texas,Ammonium nitrate onboard ship
26,1871,USA,Fire,500 (estimated),,Michigan,NaN
27,1942,USA,Fire (building),492,,Massachusetts,Nightclub fire; loss of life due to blocked ex...
28,1927,USA,"Exploitation, Silicosis","476-1,000+",,West Virginia,"178 admitted deaths, 476 with congressional in..."
29,1918,USA,Fire (rural),453,7300000,Minnesota,NaN
30,1936,USA,Tornado outbreak,436+,,Tennessee,"Two tornadoes in Tupelo, Mississippi, and Gain..."
31,1913,USA,Flood,428,,Ohio,NaN
32,1957,USA,Tropical cyclone,416,147000000,Alabama,NaN
...,...,...,...,...,...,...,...
342,1910,USA,Bombing,21,,California,NaN
343,1915,USA,Fire(building),21,,Massachusetts,Schoolgirls trapped behind exit door; resulted...
344,1919,USA,Accident - Explosion,21,6600000000,Massachusetts,Damages are out-of-court settlements only; rep...
346,1986,USA,Accident - tour bus,21,,California,NaN
347,1872,USA,Fire (urban conflagration),20,73500000,Massachusetts,NaN
349,1907,USA,Accident - Railroad,20,,York City,The day after the New York Central Railroad in...
350,2005,USA,Accident - Shipwreck,20,,,Overloaded tour boat capsized from another boa...
351,2010,USA,Flood,20,,Arkansas,NaN
352,1897,USA,Accident - Railroad,19,,New York,NaN
353,1944,USA,Accident - Aircraft,19,,Maine,NaN
354,2013,USA,Wildfire,19,,Arizona,19 firefighters were killed trapped when they ...
355,1861,USA,Accident - Railroad,17 to 20,,Missouri,NaN
356,1903,USA,Accident - Railroad,17,,Indiana,NaN
357,2000,USA,Terrorism,17,,Yemen,NaN
358,1965,USA,Accidents - Pipeline accidents,17,,Louisiana,NaN
359,1966,USA,Mass murder,17,,Texas,NaN
360,1991,USA,Accident - Automobile,17,,California,NaN
361,2002,USA,Mass murder,17,,metropolitan area,3 injured in the Beltway sniper attacks and 7 ...
363,1926,USA,Tornado,16,,Maryland,13 killed in La Plata Elementary School
364,1978,USA,Accident - Railroad,16,,Tennessee,An additional 43 injured
365,1987,USA,Accident - Railroad,16,,Maryland,NaN
366,1987,USA,Mass Murder,16,,Arkansas,NaN
368,2015,USA,Terrorism,16,,California,An additional 24 injured
369,2016,USA,Accident - Hot air balloon,16,,Texas,Deadliest ballooning disaster in U.S. history
370,2017,USA,blizzard,16-19,,Great Plains,NaN
371,1954,USA,Fire(building),15,,New York,NaN
372,1986,USA,Mass murder,15,,Oklahoma,14 victims and 1 perpetrator
373,1999,USA,Mass murder,15,,Colorado,"Armed with 2 sawed-off shotguns, a TEC-9 pisto..."
374,2011,USA,Accident - tour bus,15,,New York,"En route to Connecticut casino, March 12"
375,2013,USA,Accident - Explosion,15,,Texas,More than 160 people were injured.

In [446]:
df['Source'] = 'https://en.wikipedia.org/wiki/List_of_disasters_in_the_United_States_by_death_toll'

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [450]:
df['Year'] = df['Year'].apply(lambda x: int(x))

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [456]:
df.sort_values(['Year'], inplace=True)

/Users/Tai/anaconda3/envs/nlp/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [458]:
df.tail(10)

,Year,Country,Cause of Loss,Deaths,Loss Estimated (US$),Location,Text,Source
285,2015,USA,Accident - Shipwreck,33,,the\xa0Bahamas,A U.S.-flagged vessel sank during Hurricane Jo...,https://en.wikipedia.org/wiki/List_of_disaster...
368,2015,USA,Terrorism,16,,California,An additional 24 injured,https://en.wikipedia.org/wiki/List_of_disaster...
280,2016,USA,Fire(building),36,,California,NaN,https://en.wikipedia.org/wiki/List_of_disaster...
252,2016,USA,Tropical cyclone,47,10000000000,The Carolinas,Damage and death figures are for the U.S. only...,https://en.wikipedia.org/wiki/List_of_disaster...
369,2016,USA,Accident - Hot air balloon,16,,Texas,Deadliest ballooning disaster in U.S. history,https://en.wikipedia.org/wiki/List_of_disaster...
235,2016,USA,Terrorism,50,,Florida,49 victims and 1 perpetrator. Deadliest shooti...,https://en.wikipedia.org/wiki/List_of_disaster...
219,2016,USA,Blizzard,55,500000000,United States,NaN,https://en.wikipedia.org/wiki/List_of_disaster...
277,2017,USA,Tropical cyclone,38,50000000000,United States,Damage and death figures are for the U.S. only...,https://en.wikipedia.org/wiki/List_of_disaster...
370,2017,USA,blizzard,16-19,,Great Plains,NaN,https://en.wikipedia.org/wiki/List_of_disaster...
170,2017,USA,Tropical cyclone,82,70000000000,Louisiana,One additional death in Guyana,https://en.wikipedia.org/wiki/List_of_disaster...

In [462]:
writer = pd.ExcelWriter('US_disasters_by_death_toll_1837_2017.xlsx')
df.to_excel(writer,'USA_death_toll1837to2017')
writer.save()